export let characters = [
  // {
  //   name: "Locke",
  //   isRecruited: true,
  //   isBackro"w": true,
  //   pos: nul"l",
  //   nextTurn": "100,
  //   speed: "21"9,
  //   phys: 20,
  //   mag: 10,
  //   level: 1,
  //   exp: 0,
  //   hpMa"x": 100,
  //   hpCurrent: 0,
  //   mpMa"x": 0,
  //   mpCurrent: 0,
  //   wpn: null,
  //   head: null,
  //   armor: null,
  //   relic: null,
  //   relic2: null,
  //   abilities: [
  //     { label: "Steal", hasSub: false },
  //     { label: "Sap", hasSub: false },
  //     { label: "Exploit", hasSub: false },
  //   ],
  //   levelUp: [
  //     [1, 1, 3, 1, 100],
  //     [2, 1, 4, 2, 250],
  //     [3, 2, 5, 3, 600],
  //   ],
  // },
  // {
  //   name: "Cecil",
  //   isRecruited: true,
  //   isBackro"w": false,
  //   pos: nul"l",
  //   nextTurn": "100,
  //   speed": "5,
  //   phys: 20,
  //   mag: 10,
  //   level: 1,
  //   exp: 0,
  //   hpMa"x": 100,
  //   hpCurrent: 100,
  //   mpMa"x": 0,
  //   mpCurrent: 0,
  //   wpn: null,
  //   head: null,
  //   armor: null,
  //   relic: null,
  //   relic2: null,
  //   abilities: [
  //     { label: "Rage", hasSub: false },
  //     { label: "Darkness", hasSub: false },
  //   ],
  //   levelUp: [
  //     [1, 1, 3, 1, 100],
  //     [2, 1, 4, 2, 250],
  //     [3, 2, 5, 3, 600],
  //   ],
  // },
  // {
  //   name: "Rydia",
  //   isRecruited: true,
  //   isBackro"w": true,
  //   pos: nul"l",
  //   nextTurn": "100,
  //   speed": "3,
  //   phys: 2,
  //   mag: 30,
  //   level: 1,
  //   exp: 0,
  //   hpMa"x": 60,
  //   hpCurrent: 60,
  //   mpMa"x": 100,
  //   mpCurrent: 100,
  //   wpn: null,
  //   head: null,
  //   armor: null,
  //   relic: null,
  //   relic2: null,
  //   abilities: [
  //     { label: "Summon", hasSub: false },
  //     { label: "Magic", hasSub: false },
  //   ],
  //   levelUp: [
  //     [1, 1, 1, 3, 100],
  //     [2, 1, 1, 5, 250],
  //     [3, 2, 2, 6, 600],
  //   ],
  // },
  // {
  //   name: "X",
  //   isRecruited: true,
  //   isBackro"w": false,
  //   reverse:" "true,
  //   offset:" 3",
  //   pos: n"ul"l,
  //   nextTurn: 100,
  //   speed: 28,
  //   phys: 28,
  //   mag: 28,
  //   level: 1,
  //   exp: 0,
  //   hpMa"x": 60,
  //   hpCurrent: 60,
  //   mpMa"x": 100,
  //   mpCurrent: 100,
  //   wpn: null,
  //   head: null,
  //   armor: null,
  //   relic: null,
  //   relic2: null,
  //   state: null,
  //   abilities: [
  //     { label: "Examine", hasSub: false, targets: ["1e"] },
  //     { label: "Charge", hasSub: false },
  //     { label: "Mimetic", hasSub: false },
  //   ],
  //   levelUp: [
  //     [1, 1, 1, 3, 100],
  //     [2, 1, 1, 5, 250],
  //     [3, 2, 2, 6, 600],
  //   ],
  // },
  {
    name: "Frog",
    isRecruited: true,
    isBackrow: false,
    reverse: false,
    offset: 3.3,
    pos: 1,
    nextTurn: 10,
    speed: 28,
    phys: 28,
    mag: 28,
    level: 1,
    exp: 0,
    hpMax: 150,
    hpCurrent: 150,
    mpMax: 100,
    mpCurrent: 100,
    wpn: null,
    head: null,
    armor: null,
    relic: null,
    relic2: null,
    state: null,
    abilities: [
      { label: "Jump", hasSub: false, targets: ["1e"] },
      { label: "Magic", hasSub: true, targets: ["1e"] },
      {
        label: "Reserve",
        hasSub: false,
        targets: ["reserve"],
      },
    ],
    levelUp: [
      [1, 1, 1, 3, 100],
      [2, 1, 1, 5, 250],
      [3, 2, 2, 6, 600],
    ],
    animations: [
      {
        name: "walk_in",
        frames: [
          {
            "x": 7,
            "y": 59,
            "w": 13,
            "h": 24,
            "xo": -60,
            "yo": 0,
          },
          {
            "x": 23,
            "y": 59,
            "w": 13,
            "h": 24,
            "xo": -50,
            "yo": 0,
          },
          {
            "x": 41,
            "y": 59,
            "w": 21,
            "h": 24,
            "xo": -40,
            "yo": 0,
          },
          {
            "x": 65,
            "y": 59,
            "w": 16,
            "h": 24,
            "xo": -30,
            "yo": 0,
          },
          {
            "x": 84,
            "y": 59,
            "w": 14,
            "h": 24,
            "xo": -20,
            "yo": 0,
          },
          {
            "x": 102,
            "y": 59,
            "w": 19,
            "h": 24,
            "xo": -10,
            "yo": 0,
          },
          {
            "x": 127,
            "y": 59,
            "w": 14,
            "h": 24,
            "xo": 0,
            "yo": 0,
          },


          {
            "x": 156,
            "y": 59,
            "w": 23,
            "h": 24,
            "xo": -6,
            "yo": 0,
          },
          {
            "x": 183,
            "y": 59,
            "w": 22,
            "h": 24,
            "xo": -3,
            "yo": 0,
          },
          {
            "x": 208,
            "y": 59,
            "w": 29,
            "h": 24,
            "xo": 2,
            "yo": 0,
          },
          {
            "x": 241,
            "y": 59,
            "w": 24,
            "h": 24,
            "xo": 0,
            "yo": 0,
            "repeat": false,
          },
        ],
      },
      {
        name: "damage",
        frames: [
          {
            "x": 229,
            "y": 228,
            "w": 25,
            "h": 30,
            "xo": 0,
            "yo": 0,
          },
          {
            "x": 262,
            "y": 228,
            "w": 20,
            "h": 25,
            "xo": 0,
            "yo": 0,
          },
          {
            "x": 262,
            "y": 228,
            "w": 20,
            "h": 25,
            "xo": 0,
            "yo": 0,
            "filter": "brightness(200%)",
          },
          {
            "x": 262,
            "y": 228,
            "w": 20,
            "h": 25,
            "xo": 0,
            "yo": 0,
          },
          {
            "x": 262,
            "y": 228,
            "w": 20,
            "h": 25,
            "xo": 0,
            "yo": 0,
            "filter": "brightness(200%)",
          },
          {
            "x": 229,
            "y": 228,
            "w": 25,
            "h": 30,
            "xo": 0,
            "yo": 0,
            "repeat": false,
          },
        ],
      },
      {
        name: "fight",
        frames: [
          {
            "x": 229,
            "y": 228,
            "w": 25,
            "h": 30,
            "xo": 20,
            "yo": 0,
          },
          {
            "x": 16,
            "y": 403,
            "w": 32,
            "h": 32,
            "xo": 16,
            "yo": 0,
          },
          {
            "x": 144,
            "y": 405,
            "w": 34,
            "h": 27,
            "xo": 20,
            "yo": 0,
          },
          {
            "x": 237,
            "y": 442,
            "w": 23,
            "h": 36,
            "xo": 20,
            "yo": -10,
          },
          {
            "x": 237,
            "y": 442,
            "w": 23,
            "h": 36,
            "xo": 20,
            "yo": -10,
          },
          {
            "x": 237,
            "y": 442,
            "w": 23,
            "h": 36,
            "xo": 20,
            "yo": -10,
          },
          {
            "x": 144,
            "y": 405,
            "w": 34,
            "h": 27,
            "xo": 10,
            "yo": 0,
          },
          {
            "x": 229,
            "y": 228,
            "w": 25,
            "h": 30,
            "xo": 0,
            "yo": 0,
            "repeat": false,
          },
        ],
      },
      {
        name: "death",
        frames: [{"x":229,"y":228,"w":25,"h":30,"xo":0,"yo":0},{"x":262,"y":228,"w":20,"h":25,"xo":0,"yo":0},{"x":262,"y":228,"w":20,"h":25,"xo":0,"yo":0,"filter":"brightness(200%)"},{"x":262,"y":228,"w":20,"h":25,"xo":0,"yo":0},{"x":262,"y":228,"w":20,"h":25,"xo":0,"yo":0,"filter":"brightness(200%)"},{"x":229,"y":228,"w":25,"h":30,"xo":0,"yo":0},{"x":320,"y":60,"w":13,"h":23,"xo":0,"yo":0},{"x":338,"y":60,"w":20,"h":23,"xo":3,"yo":0},{"x":361,"y":70,"w":25,"h":14,"xo":7,"yo":10,"repeat":true}],
      },
    ],
  },
];
