export let enemies = [
  {
    name: "Goblin",
    sprite: "goblin",
    nextTurn: 100,
    speed: 30,
    phys: 1,
    mag: 1,
    level: 1,
    exp: 2,
    hpMax: 20,
    hpCurrent: 20,
    mpMax: 0,
    mpCurrent: 0,
    abilities: ["Fight"],
  },
  {
    name: "Goblin Commander",
    sprite: "goblin",
    filter: "redShift",
    nextTurn: 100,
    speed: 255,
    phys: 1,
    mag: 1,
    level: 1,
    exp: 2,
    hpMax: 80,
    hpCurrent: 80,
    mpMax: 0,
    mpCurrent: 0,
    abilities: ["Fight"],
  },
  {
    name: "Bat",
    sprite: "bat",
    nextTurn: 100,
    speed: 25,
    phys: 1,
    mag: 1,
    level: 1,
    exp: 2,
    hpMax: 20,
    hpCurrent: 20,
    mpMax: 0,
    mpCurrent: 0,
    abilities: ["Fight"],
  },
];
