export let sounds = [
  "ff6-00BlueMagic.wav",
  "ff6-01BlackMagic.wav",
  "ff6-02WhiteMagic.wav",
  "ff6-03BlackMagic2.wav",
  "ff6-04RunAway.wav",
  "ff6-05Ultima.wav",
  "ff6-06InFerno.wav",
  "ff6-07Haste.wav",
  "ff6-08DragonEsper.wav",
  "ff6-09Scan.wav",
  "ff6-0ARasp.wav",
  "ff6-0BRasp2.wav",
  "ff6-0CLaserAtk.wav",
  "ff6-0DMiss.wav",
  "ff6-0EDragonAttack.wav",
  "ff6-0FEerie.wav",
  "ff6-10CanonExplosion.wav",
  "ff6-11idk.wav",
  "ff6-12InfernoShort.wav",
  "ff6-13Explosion.wav",
  "ff6-14EsperAttack.wav",
  "ff6-15Bolt3.wav",
  "ff6-16Fire1.wav",
  "ff6-17Ting.wav",
  "ff6-18Ice1.wav",
  "ff6-19Fire3.wav",
  "ff6-1AMeteor.wav",
  "ff6-1BItemMenuItng.wav",
  "ff6-1CIdk.wav",
  "ff6-1DImpSecondPart.wav",
  "ff6-1EPhoenixDown.wav",
  "ff6-1FDemiShort.wav",
  "ff6-20Poison.wav",
  "ff6-21ConstantPunching.wav",
  "ff6-22Bio.wav",
  "ff6-25MeteorShorter.wav",
  "ff6-26Idk.wav",
  "ff6-27EerieShort.wav",
  "ff6-28Thief.wav",
  "ff6-29SaveTingEcho.wav",
  "ff6-2AHealingSpellFirstPart.wav",
  "ff6-2BWindlike.wav",
  "ff6-2CDoorOpen.wav",
  "ff6-2DMonsterDeath.wav",
  "ff6-2ESwordSlashLong.wav",
  "ff6-2fElixir.wav",
  "ff6-30TempestLike.wav",
  "ff6-31FlarePart1.wav",
  "ff6-32Mecha.wav",
  "ff6-33HitFist.wav",
  "ff6-34CurativeItem.wav",
  "ff6-35BreakSpell.wav",
  "ff6-36Ice2Part1.wav",
  "ff6-37Ice2Part2.wav",
  "ff6-38ImpSpellPart1.wav",
  "ff6-39Muddle.wav",
  "ff6-3AHugeSpell.wav",
  "ff6-3Cidk.wav",
  "ff6-3DBolt2.wav",
  "ff6-3EPeral.wav",
  "ff6-3FBigInferno.wav",
  "ff6-3bBuffProtect.wav",
  "ff6-40CyanSwdtechActivation.wav",
  "ff6-41MultipleTing.wav",
  "ff6-42Fire2.wav",
  "ff6-43Bolt1.wav",
  "ff6-44Ting.wav",
  "ff6-45Shell.wav",
  "ff6-46EsperPartyDisappear.wav",
  "ff6-47Ting.wav",
  "ff6-4BDrill.wav",
  "ff6-4CLife.wav",
  "ff6-4DIce3.wav",
  "ff6-4EDeathSpell.wav",
  "ff6-4FLagomorph.wav",
  "ff6-50Idk.wav",
  "ff6-51Machine.wav",
  "ff6-52SwdTechStunner.wav",
  "ff6-53Idk.wav",
  "ff6-54Idk.wav",
  "ff6-55Idk.wav",
  "ff6-56Boomerang.wav",
  "ff6-57Idk.wav",
  "ff6-58Vanish.wav",
  "ff6-59greenCherry.wav",
  "ff6-5ASaveTing.wav",
  "ff6-5BThiefSteal.wav",
  "ff6-64HighSwdtech.wav",
  "ff6-65SwordSlash.wav",
  "ff6-66Bioblaster.wav",
  "ff6-66CureSpellPart1.wav",
  "ff6-67EsperShining.wav",
  "ff6-68Snare.wav",
  "ff6-69Osmose.wav",
  "ff6-6AJumpDragonboots.wav",
  "ff6-6BBlaster.wav",
  "ff6-6CEsperRoar.wav",
  "ff6-6DThamasian.wav",
  "ff6-6EWind.wav",
  "ff6-6FRetort.wav",
  "ff6-70Weird.wav",
  "ff6-71EerieWave.wav",
  "ff6-72BigWind.wav",
  "ff6-73NarsheWind.wav",
  "ff6-74KefkaAttack.wav",
  "ff6-75MechanicWalk.wav",
  "ff6-76Harvester.wav",
  "ff6-77Beat.wav",
  "ff6-78Closing.wav",
  "ff6-79Aquarake.wav",
  "ff6-7APossess.wav",
  "ff6-7BMechanic.wav",
  "ff6-7CBoom.wav",
  "ff6-7DHealingSound.wav",
  "ff6-7EEarthquakeLow.wav",
  "ff6-7FMechDispatch.wav",
  "ff6-80LongFireball.wav",
  "ff6-81ZapAqua.wav",
  "ff6-82Drill.wav",
  "ff6-87WallChange.wav",
  "ff6-88.wav",
  "ff6-89Exploder.wav",
  "ff6-8ADirkSlash.wav",
  "ff6-8BClawSlash.wav",
  "ff6-8BSaveTing.wav",
  "ff6-8CRodHit.wav",
  "ff6-8DIdk.wav",
  "ff6-8FDemi.wav",
  "ff6-90AirAnchor.wav",
  "ff6-91Idk.wav",
  "ff6-92TrainHorn.wav",
  "ff6-97Bark.wav",
  "ff6-98DoorEcho.wav",
  "ff6-99DoorDistant.wav",
  "ff6-9AMoveLove.wav",
  "ff6-9BScratch.wav",
  "ff6-9CMsleSky.wav",
  "ff6-9DGrow.wav",
  "ff6-9EPhoenixDown.wav",
  "ff6-9FBlockSword.wav",
  "ff6-A0BlockShield.wav",
  "ff6-A1CurativeItem.wav",
  "ff6-A2Flare.wav",
  "ff6-A3Zap.wav",
  "ff6-A4SwordSlash.wav",
  "ff6-A5Earthquake.wav",
  "ff6-A6Switch.wav",
  "ff6-A7WeirdBeat.wav",
  "ff6-A8SwordSlash.wav",
  "ff6-A9ObjectMove.wav",
  "ff6-AAHealingWind.wav",
  "ff6-ABExploder.wav",
  "ff6-ACQuadraSlice.wav",
  "ff6-ADDemiShort.wav",
  "ff6-AECinema.wav",
  "ff6-AFTentacle.wav",
  "ff6-B0MachinePowerUp.wav",
  "ff6-B1HealingWind.wav",
  "ff6-B2Cinema.wav",
  "ff6-B3dk.wav",
  "ff6-B4Explosion.wav",
  "ff6-B5LilHit.wav",
  "ff6-B6ElfFire.wav",
  "ff6-B7Explosio.wav",
  "ff6-B8Whistle.wav",
  "ff6-B9TerraScream.wav",
  "ff6-BAFallingDown.wav",
  "ff6-BBBigClose.wav",
  "ff6-BCLilPummel.wav",
  "ff6-BDMachineRay.wav",
  "ff6-BEDeathToll.wav",
  "ff6-BFBuyingSelling.wav",
  "ff6-C0Bird.wav",
  "ff6-C1Encounter.wav",
  "ff6-C2Ting.wav",
  "ff6-C3GauRoar.wav",
  "ff6-C4MachineRayShort.wav",
  "ff6-C5Cure1Part2.wav",
  "ff6-C6SAVETING.wav",
  "ff6-C7ChestClose.wav",
  "ff6-C8idk.wav",
  "ff6-C9SwdTech.wav",
  "ff6-CBCureSpellPart2.wav",
  "ff6-CCHitEcho.wav",
  "ff6-CDKefkaLaugh.wav",
  "ff6-CEWaterSplash.wav",
  "ff6-CFMachineBoomerang.wav",
  "ff6-CineGiveObject.wav",
  "ff6-D0OperaWhite.wav",
  "ff6-D0idk.wav",
  "ff6-D1Ting.wav",
  "ff6-D2FireCine.wav",
  "ff6-D3Zap.wav",
  "ff6-D4NoiseBlaster.wav",
  "ff6-D5idk.wav",
  "ff6-D6LongWind.wav",
  "ff6-D8Bubble.wav",
  "ff6-D8NoiseBlaster.wav",
  "ff6-D9Chocobo.wav",
  "ff6-DAFlailHit.wav",
  "ff6-DBClose.wav",
  "ff6-DCMenuTing.wav",
  "ff6-DDAlarm.wav",
  "ff6-DFCharge.wav",
  "ff6-DFTrainstoppinMaybe.wav",
  "ff6-E3OpenHuge.wav",
  "ff6-EBRainSpell.wav",
  "ff6-ECHeartBeat.wav",
  "ff6-EDTrainStrarting.wav",
  "ff6-EECureInMenu.wav",
  "ff6-EFBossAppearingEscaping.wav",
  "ff6-F0DistantBoom.wav",
  "ff6-F1ZapCharge.wav",
  "ff6-F2BossDeath.wav",
  "ff6-F3DiceThrown.wav",
  "ff6-F4WindCharge.wav",
  "ff6-F5FightTing.wav",
  "ff6-F6BigEarthQuake.wav",
  "ff6-F7CloseBigNear.wav",
  "ff6-F8DemiFlare.wav",
  "ff6-F9Mog.wav",
  "ff6-FADice2.wav",
  "ff6-FBGhostMusic.wav",
  "ff6-FCMenuTing2.wav",
  "ff6-Runic.wav",
  "ff6-SafeProtect.wav",
  "ff6-esperCry.wav",
  "ff6-hugeAttack.wav",
  "ff6-idk13.wav",
  "ff6-idk14.wav",
  "ff6-idk15.wav",
  "ff6-idk16.wav",
  "ff6-idk17.wav",
  "ff6-idk18.wav",
  "ff6-idk20.wav",
  "ff6-idkAfterlagomorph.wav",
  "ff6-littleinferno.wav",
  "ff6-runaway.wav",
  "ff6-smallEsplosion.wav",
  "MMX - Alert 1.wav",
  "MMX - Alert 2.wav",
  "MMX - Armadillo Charge.wav",
  "MMX - Armadillo Laser.wav",
  "MMX - Beam Pulse.wav",
  "MMX - Beep (1).wav",
  "MMX - Beep (2).wav",
  "MMX - Beep (3).wav",
  "MMX - Beep (4).wav",
  "MMX - Beep (5).wav",
  "MMX - Big Hit.wav",
  "MMX - Boomer Kuwanger Teleport.wav",
  "MMX - Boss Door Close.wav",
  "MMX - Bulldozer.wav",
  "MMX - Can't Exit.wav",
  "MMX - Chill Penguin Breath.wav",
  "MMX - Door Open.wav",
  "MMX - Eagle's Tornado.wav",
  "MMX - Electric Bolt.wav",
  "MMX - Enemy Die (1).wav",
  "MMX - Enemy Die (2).wav",
  "MMX - Enemy Die (3).wav",
  "MMX - Enemy Die (4).wav",
  "MMX - Enemy Helmet Hit.wav",
  "MMX - Enemy Missle Fire.wav",
  "MMX - Enemy Motor 1.wav",
  "MMX - Enemy Motor 2.wav",
  "MMX - Enemy Motor 3.wav",
  "MMX - Enemy Sound (01).wav",
  "MMX - Enemy Sound (02).wav",
  "MMX - Enemy Sound (03).wav",
  "MMX - Enemy Sound (04).wav",
  "MMX - Enemy Sound (05).wav",
  "MMX - Enemy Sound (06).wav",
  "MMX - Enemy Sound (07).wav",
  "MMX - Enemy Sound (08).wav",
  "MMX - Enemy Sound (09).wav",
  "MMX - Enemy Sound (10).wav",
  "MMX - Enemy Sound (11).wav",
  "MMX - Enemy Sound (12).wav",
  "MMX - Energy Tank Full.wav",
  "MMX - Energy Tank Health.wav",
  "MMX - Flame Mammoth.wav",
  "MMX - Heavy Machine (1).wav",
  "MMX - Heavy Machine (2).wav",
  "MMX - Heavy Machine (3).wav",
  "MMX - Heavy Machine (4).wav",
  "MMX - Heavy Machine (5).wav",
  "MMX - Heavy Machine (6).wav",
  "MMX - Heavy Machine (7).wav",
  "MMX - Heavy Machine (8).wav",
  "MMX - Ice Break.wav",
  "MMX - Ice Freeze.wav",
  "MMX - Ice.wav",
  "MMX - Intro Data Screen.wav",
  "MMX - Mechanical Hum 1.wav",
  "MMX - Mechanical Hum 2.wav",
  "MMX - Mechanical Hum 3.wav",
  "MMX - Misc. dash, jump, move (1).wav",
  "MMX - Misc. dash, jump, move (2).wav",
  "MMX - Misc. dash, jump, move (3).wav",
  "MMX - Misc. dash, jump, move (4).wav",
  "MMX - Misc. dash, jump, move (5).wav",
  "MMX - Misc. dash, jump, move (6).wav",
  "MMX - Misc. dash, jump, move (7).wav",
  "MMX - Octopus Drain.wav",
  "MMX - Robot Suit (1).wav",
  "MMX - Robot Suit (2).wav",
  "MMX - Robot Suit (3).wav",
  "MMX - Robot Suit (4).wav",
  "MMX - Robot Suit (5).wav",
  "MMX - Robot Suit (6).wav",
  "MMX - Robot Suit (7).wav",
  "MMX - Rocks (1).wav",
  "MMX - Rocks (2).wav",
  "MMX - Rocks (3).wav",
  "MMX - Sigma Dog.wav",
  "MMX - Sigma Teleport.wav",
  "MMX - Small Hit.wav",
  "MMX - Spark Mandrill Punch.wav",
  "MMX - Spring 1.wav",
  "MMX - Spring 2.wav",
  "MMX - Stage Cursor Move.wav",
  "MMX - Submarine 1.wav",
  "MMX - Submarine 2.wav",
  "MMX - Text Letter.wav",
  "MMX - Underwater Bubble.wav",
  "MMX - Underwater Sound.wav",
  "MMX - Unknown (1).wav",
  "MMX - Unknown (2).wav",
  "MMX - Unknown (3).wav",
  "MMX - Wing Flap (1).wav",
  "MMX - Wing Flap (2).wav",
  "MMX - Wing Flap (3).wav",
  "MMX - Wing Flap (4).wav",
  "MMX - Wing Flap (5).wav",
  "MMX - X Boomerang Cutter 1.wav",
  "MMX - X Boomerang Cutter 2.wav",
  "MMX - X Chameleon Sting (Charged).wav",
  "MMX - X Chameleon Sting.wav",
  "MMX - X Charge + Shot.wav",
  "MMX - X Charge + Super Shot.wav",
  "MMX - X Charge Shot.wav",
  "MMX - X Charge.wav",
  "MMX - X Dash.wav",
  "MMX - X Die.wav",
  "MMX - X Electric Spark.wav",
  "MMX - X Extra Life.wav",
  "MMX - X Fade In.wav",
  "MMX - X Fade Out.wav",
  "MMX - X Fire Wave.wav",
  "MMX - X Homing Torpedo.wav",
  "MMX - X Hurt.wav",
  "MMX - X Jump.wav",
  "MMX - X Land.wav",
  "MMX - X Life Gain.wav",
  "MMX - X Powerup Infuse.wav",
  "MMX - X Regular Shot.wav",
  "MMX - X Rolling Shield.wav",
  "MMX - X Rolling Shiled (Charged).wav",
  "MMX - X Storm Tornado.wav",
  "MMX - X Sub Tank-Heart Powerup.wav",
  "MMX - X Super Charge Shot.wav",
  "MMX - X Upgrade Complete.wav",
  "MMX - unknown (4).wav",
  "ct-alarm.ogg",
  "ct-alert.ogg",
  "ct-attack.ogg",
  "ct-attack_alt.ogg",
  "ct-aura_glow.ogg",
  "ct-bats.ogg",
  "ct-battleStart.ogg",
  "ct-battleTurn.ogg",
  "ct-bekklerLose.ogg",
  "ct-bigWin.ogg",
  "ct-burning.ogg",
  "ct-burst.ogg",
  "ct-chant.ogg",
  "ct-charm1.ogg",
  "ct-charm2.ogg",
  "ct-confuseTech.ogg",
  "ct-continum.ogg",
  "ct-croak.ogg",
  "ct-crushingSlash.ogg",
  "ct-cureMagic.ogg",
  "ct-cursor.ogg",
  "ct-deltaForce.ogg",
  "ct-deltaStorm.ogg",
  "ct-draw.ogg",
  "ct-drip.ogg",
  "ct-electricArc.ogg",
  "ct-enemyDie.ogg",
  "ct-epochLaunch.ogg",
  "ct-exhaust.ogg",
  "ct-explosion.ogg",
  "ct-fall.ogg",
  "ct-fireMagic.ogg",
  "ct-flap_once.ogg",
  "ct-flapping.ogg",
  "ct-flapping_loop.ogg",
  "ct-gainHp.ogg",
  "ct-gainMp.ogg",
  "ct-gateActivate.ogg",
  "ct-getItem.ogg",
  "ct-grunt.ogg",
  "ct-gulls.ogg",
  "ct-heckran.ogg",
  "ct-iceMagic.ogg",
  "ct-jumpTech.ogg",
  "ct-lavos music clip.ogg",
  "ct-lavos.ogg",
  "ct-lavosHeart.ogg",
  "ct-lavosRain.ogg",
  "ct-leeneBell.ogg",
  "ct-lightning.ogg",
  "ct-lightningMagic.ogg",
  "ct-loseMusic.ogg",
  "ct-magicBlast.ogg",
  "ct-megaBomb.ogg",
  "ct-miss.ogg",
  "ct-monsterRoar1.ogg",
  "ct-monsterRoar2.ogg",
  "ct-onscreen.ogg",
  "ct-organ.ogg",
  "ct-ozzie.ogg",
  "ct-pat.ogg",
  "ct-pat_3x (padded).ogg",
  "ct-pat_3x.ogg",
  "ct-portal reverb.ogg",
  "ct-portal.ogg",
  "ct-roboReady.ogg",
  "ct-roboTech.ogg",
  "ct-robo_talk.ogg",
  "ct-rumble.ogg",
  "ct-rustle.ogg",
  "ct-sad music clip.ogg",
  "ct-savePoint.ogg",
  "ct-sealedBoxMusic.ogg",
  "ct-shadowMagic.ogg",
  "ct-shot.ogg",
  "ct-slash1.ogg",
  "ct-slash2.ogg",
  "ct-slash3.ogg",
  "ct-sleepMusic.ogg",
  "ct-spinout.ogg",
  "ct-squeak.ogg",
  "ct-step.ogg",
  "ct-swish.ogg",
  "ct-thump1.ogg",
  "ct-thump2.ogg",
  "ct-type.ogg",
  "ct-tyrano.ogg",
  "ct-useHealingItem.ogg",
  "ct-waterMagic.ogg",
  "ct-wrong.ogg",
];
